---
- name: Create Jenkins group
  group:
    name: jenkins
    state: present
- name: Create Jenkins user
  user:
    name: jenkins
    group: jenkins
- name: Install Build Pipeline Plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    state: latest
    params: "{{ jenkins_params_plugins }}"
- name: Install Publish Over SSH Plugin
  jenkins_plugin:
    name: publish-over-ssh
    state: latest
    params: "{{ jenkins_params_plugins }}"
- name: Install SSH Plugin
  jenkins_plugin:
    name: ssh
    state: latest
    params: "{{ jenkins_params_plugins }}"
- name: Install SonarQube Plugin
  jenkins_plugin:
    name: sonar
    state: latest
    params: "{{ jenkins_params_plugins }}"
- name: Install Artifactory Plugin
  jenkins_plugin:
    name: artifactory
    state: latest
    params: "{{ jenkins_params_plugins }}"
- name: Install dependencies
  pip:
    name: "{{item}}"
    state: latest
  with_items:
    - jenkins-python
    - lxml
- name: Create Build job
  jenkins_job:
    config: "{{ lookup('template', 'templates/build.xml.j2') }}"
    name: build
    url:  "{{ jenkins_url }}"
    user: "{{ jenkins_user }}"
    password: "{{ jenkins_pass }}"
