---
- name: Create Jenkins group
  group:
    name: jenkins
    state: present
- name: Create Jenkins user
  user:
    name: jenkins
    group: jenkins
- name: Install Build Pipeline Plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    with_dependencies: yes
    params: "{{ jenkins_params_plugins }}"
